### ISSUE TITLE
Get a deployment service for testing and demoing

### ISSUE THREAD

**Issue by StoneyJackson** [LibreFoodPantry/Community#22]
Example deployment service: Heroku and Google Cloud.

CI is great for automated testing. But we need a way for developers, product owners, and clients to easily test a new feature. Easily means not having to install, configure, and run the system manually. So we are talking about continuous deployment to a demo service.

We need an account with a service that can be used across LFP projects for this purpose.

**Comment by StoneyJackson** [comment]
@kwurst Is this done? I ask because I thought I saw an email about LFP having a Heroku account?

If this is done, we probably need to figure out how to use it :) And maybe provide some instructions or links to instruction for using it.

**Comment by kwurst** [comment]
Yes, we have a Heroku account. Yes, we need to figure out how to use it. 

Currently, it is running the FoodKeeperAPI app. We can probably figure it out from there...

**Comment by StoneyJackson** [comment]
OK, so we have it. I've added a documentation issue to ProjectTemplate. But this issue is done.
