### ISSUE TITLE
Need a website for LibreFoodPantry

### ISSUE THREAD

**Issue by StoneyJackson** [LibreFoodPantry/Community#30]
Much of what is on the README.md of this project (e.g., Vision, Mission, etc.) probably belongs on a separate website for LibreFoodPantry. The README.md of this project should explain the purpose of the Community project, what belongs in its issue tracker, and how to get involved.

I propose using GitHub pages to create a website for LFP: https://pages.github.com/ .

**Comment by kwurst** [comment]
We should register librefoodpantry.org. We can have Software Freedom Conservancy hold the URL through Teaching Open Source. TOS can probably pay the yearly registration fee. Should I ask TOS Coordinating Committee at October meeting? Or do we want to try to do this sooner?

**Comment by StoneyJackson** [comment]
I agree. Sooner is better. If we get it now I assume we can transfer to TOS later. Worst case we get stuck with the bill for the first year. I'll split it with you if that happens.

Should we make a new issue for this? Although related both can be done independently.

**Comment by kwurst** [comment]
librefoodpantry.org registered #44

**Comment by kwurst** [comment]
librefoodpantry.github.io has been created from the README.md in LibreFoodPantry/Community as a first draft.

librefoodpantry.org has been pointed at librefoodpantry.github.io

Viola! We have a website. Now people can start putting in issues for what should go on the website...
