### ISSUE TITLE
Adopt Developer Certification of Origin

### ISSUE THREAD

**Issue by StoneyJackson** [LibreFoodPantry/Community#32]
Do we want to adopt Developer Certification of Origin (DCO)?

This article provides an overview of CLAs and DCOs, what they are for, and which a project might choose. https://opensource.com/article/18/3/cla-vs-dco-whats-difference

This site describes how to use DCO and also shows that it can be added as an automated check when a pull request is made. https://github.com/apps/dco

Impact
-------

- Add a CDO file to the root of each project.
- Add an explanation of CDO and how to sign off commits in the CONTRIBUTING file.
- Enable an automated check on each project to check that each commit has been signed off.
- Every commit must be signed off by the committer.

**Comment by hislop** [comment]
I think this would be a good idea simply because it would introduce the idea to students.

**Comment by StoneyJackson** [comment]
Reopened because I've been documenting some of the workflow, and I've coming across some cases where DCO may cause pain.

Case 1: A team is working on a pull-request. Different authors have made commits. After some time, someone notices that several of the commits have not been Signed-off-by the author. Fixing this requires rebasing, which is non-trivial (especially to get the team and possibly reviewers back in synch), will mess up any review information done through GitHub, and may cause problems for the team as they will have to perform some more git magic.

Case 2: I'm trying to integrate [conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.4/) into the workflow to allow the automatic generation of changelogs and version numbers for releases. It appears that the common way to do this is using a squash an merge policy, which means squashing all the commits on a pull-request into a single commit and then rebasing it onto master and then fast-forwarding master. Anyway... with DCO, squashing is a bad idea since the sign-offs would be lost in the squash.

So then I was thinking through how to allow a simple merge-commit policy. This preserves all the commits (yeah!). And in fact allows the crafting and reviewing of a merge-commit which can become the nice "conventional commit" we need for changelog and version number generation. Of course, the final commit message, assuming it was crafted by more than one person, should be signed-off by all those who drafted it. Although anyone could simply add "Signed-off-by" lines to the commit message, not anyone SHOULD be able to. Only the person who is signing off should be able to.

The point is, this gets complicated.

I'm not sure what the solution is. Just documenting it while it's fresh.

**Comment by StoneyJackson** [comment]
It's in ProjectTemplate. When other projects integrate ProjectTemplate, they will too. Calling this done.
