### ISSUE TITLE
Hold LFP Workflow Story Mapping Session

### ISSUE THREAD

**Issue by kwurst** [LibreFoodPantry/Community#39]
@cradkowski  has been asking questions about what the different roles in LFP
do, and need access to. I can answer most of them, but this has started
me thinking that we need do a Story Mapping session on the LFP Workflow
itself.

We need to figure out what all the roles are, what they want to do, what
they need access to. And coming up with the story for a shop from
joining the project through the "semester" would be a great thing to
have as the beginning of the documentation, as well as the information
Chris needs to set up the infrastructure.

I would like to try to do this next week before Stoney disappears. We
can do this in-person at WSU with @kwurst , @StoneyJackson , and Chris, and then have
@burdged , @lpostner , Bob, and @hislop  look it over and make suggestions.

Maybe we can try one of the online story mapping tools for this to let
people participate remotely/asynchronously...

**Comment by kwurst** [comment]
Trying out https://draft.do/ for the story mapping.

- Working out roles here: https://draft.do/7jgfp (read only)
- Working out story map here: https://draft.do/qwd9k (read only)

@StoneyJackson @cradkowski have already been given edit access.

For anyone else to request edit access, comment here.

**Comment by StoneyJackson** [comment]
@kwurst We talked by phone, but for transparency... I'm available Wed-Fri this coming week.

**Comment by StoneyJackson** [comment]
@kwurst @cradkowski 

I've made some changes to the shop-level story map.

* Combine "select work" and "claim work" columns
* Clarify which board and/or column being modified
* Normalize terms: create vs. add vs. move
* Add suggested columns for boards
* Elaborate reviewing
* Clarify when to move issues and MR between columns and boards

**Comment by kwurst** [comment]
@hislop @lpostner @burdged 

Please look at the Shop Workflow story map (https://draft.do/qwd9k), and make comments here.

Let us know what is unclear, what is missing, what we don't need.

**Comment by StoneyJackson** [comment]
I'm calling this done. If folks have questions or comments, feel free to reopen or create a new issue.

**Comment by kwurst** [comment]
Board URL has changed: https://draft.do/eyb2z

Why this happened: long story about transferring ownership to a LibreFoodPantry account 🙄
