### ISSUE TITLE
Commit story map png files as a way to version control story maps.

### ISSUE THREAD

**Issue by kwurst** [LibreFoodPantry/Community#51]
If we link to draft.do boards, then there is no record of changes to story maps.

If we export to png files and commit them when there are changes, then the committer is forced to describe the changes in the commit message. (Even if git cannot show a diff of the changes.)

**Comment by kwurst** [comment]
@StoneyJackson what do you think of this idea?

**Comment by StoneyJackson** [comment]
@kwurst That's true. OK, I'm sold. Let's store PNGs after each change. Then we can simply embed a link to the image from the roadmap web page. That has nice advantages too :)

**Comment by kwurst** [comment]
@StoneyJackson Opinions on where to commit the story map image? Probably not librefoodpantry.github.io.

Probably in Community. Top level? In a folder?

**Comment by StoneyJackson** [comment]
@kwurst Sounds good. If we're wrong, we can change it later.
