### ISSUE TITLE
GitHub vs GitLab

### ISSUE THREAD

**Issue by StoneyJackson** [LibreFoodPantry/Community#54]
We've been talking about this for a while, but I didn't see an issue for it. So I'm adding one now.

**Comment by cradkowski** [comment]
This seems like a good place for this: https://docs.google.com/spreadsheets/d/1BAeDuWQvJonCbZj5-e2yNo8HkzeFNTbyDQAEtLRIw-Y/edit?usp=sharing

**Comment by kwurst** [comment]
I vote for GitLab.

**Comment by StoneyJackson** [comment]
I vote for GitLab.

**Comment by lpostner** [comment]
I vote for GitLab

**Comment by HeidiEllis** [comment]
+1

Heidi

On 8/6/19 10:52 AM, lpostner wrote:
**** EXTERNAL MESSAGE ****

I vote for GitLab

**Comment by burdged** [comment]
I thought I had already voted for GitLab at the LFP Retreat. My vote still stands for GitLab!!

**Comment by hislop** [comment]
Seems like the result is clear!  I’m fine with going along with GitLab.

**Comment by StoneyJackson** [comment]
Decision: GitLab

Thanks all for voting and helping to make this decision!
