### ISSUE TITLE
Verify librefoodpantry.org with GitHub

### ISSUE THREAD

**Issue by StoneyJackson** [LibreFoodPantry/Community#55]
This will let others know that librefoodpantry.org is really associated with httpd://github.com/LibreFoodPantry .

See https://help.github.com/en/articles/verifying-your-organizations-domain for instructions .

**Comment by kwurst** [comment]
We can't do this, because we would need to prove that we own both librefoodpantry.org (no problem) and googlegroups.com (nope...)

**Comment by kwurst** [comment]
Maybe we need to look at setting up an email address on librefoodpantry.org. (Even if it forwards to a google group?)

**Comment by kwurst** [comment]
We now have email forwarding. I'll change the organization's email address to use the forwarding address, and then do the verification.

**Comment by kwurst** [comment]
Done!

**Comment by StoneyJackson** [comment]
:tada: :clap:
