### ISSUE TITLE
librefoodpantry.org email addresses

### ISSUE THREAD

**Issue by kwurst** [LibreFoodPantry/Community#57]
Create

- librefoodpantry@librefoodpantry.com (point to librefoodpantry@googlegroups.com?)
- coordinating-committee@librefoodpantry.com (point to librefoodpantry-coordinatingcommittee@googlegroups.com?)
- accounts@librefoodpantry.com (point to librefoodpantry-accounts@googlegroups.com?)

**Comment by kwurst** [comment]
They all work.
I am assuming we don't care about forwarding addresses from librefoodpantry.com (If we do, open a new issue.)

**Comment by StoneyJackson** [comment]
:tada:
