### ISSUE TITLE
Email for reporting violations of the code of conduct.

### ISSUE THREAD

**Issue by StoneyJackson** [LibreFoodPantry/Community#8]
## Story

As a community member, I want to report violations of the code of conduct to an email that I know is going to a small trusted group who will handle the report discretely and fairly so that I feel comfortable reporting violations.

## Background

The email in the CODE_OF_CONDUCT is currently dr.stoney@gmail.com. One would have to trust the owner of this email to handle reports appropriately. If one does not trust that person, then they would have no easy recourse.

## Proposal

Multiple emails will be listed so that a reporter can report the violation has a choice of whom to which they would like to report the violation.

## Proposed task list

Add emails of Heidi Ellis and Greg Hislop to the code of conduct.

**Comment by StoneyJackson** [comment]
Another suggestion I received by email was to get a third party ombudsman to receive reports. And then they can relay the report to the Coordinating Committee.

I like this idea.

**Comment by kwurst** [comment]
#10 may be useful for this.

**Comment by StoneyJackson** [comment]
@kwurst  I'm not sure we the general community email used as the reporting email.

**Comment by kussmaul** [comment]
> Another suggestion I received by email was to get a third party ombudsman to receive reports. 
> And then they can relay the report to the Coordinating Committee.
> 
> I like this idea.

Since @StoneyJackson likes it, I'll take credit for the suggestion. :-)
A 3rd party might help avoid potential problems if a coordinating committee member is involved in the issue (as reporter, violator, friend of either, etc). Maybe someone at SFC?

**Comment by StoneyJackson** [comment]
We decided that Heidi's, Greg's, and Stoney's emails would be the reporting emails. And that an individual can report it to any one of those emails, whichever they are most comfortable with. The code of conduct should clarify this along with providing those emails.

**Comment by StoneyJackson** [comment]
Emails added to https://github.com/LibreFoodPantry/.github/blob/master/CODE_OF_CONDUCT.md
